In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('CNN_plastic/plastic_data.csv')
df

,0,1,2,3,4,5,6,7,8,9,...,S_16,E_16,S_17,E_17,S_18,E_18,S_19,E_19,S_20,E_20
0,1,1,1,0,0,0,1,0,0,1,...,8427993.60,0.000394,8788534.74,0.000419,9148299.12,0.000443,9507407.58,0.000468,9865949.73,0.000493
1,0,1,0,0,0,1,0,1,1,0,...,10484036.59,0.000400,10988690.28,0.000425,11492630.21,0.000449,11995967.44,0.000474,12498790.43,0.000499
2,1,1,0,0,1,0,1,1,1,0,...,10646218.61,0.000391,11155598.73,0.000415,11664035.17,0.000439,12171663.97,0.000464,12678593.79,0.000488
3,0,0,1,1,0,1,1,1,1,0,...,10212384.73,0.000385,10695170.07,0.000409,11177012.19,0.000432,11658050.51,0.000457,12138390.77,0.000481
4,0,1,0,0,0,0,1,1,1,1,...,9930201.42,0.000396,10394479.73,0.000421,10858075.53,0.000446,11321092.61,0.000471,11783613.86,0.000496
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,0,0,0,1,0,1,1,0,0,1,...,15620512.61,0.000397,16464128.19,0.000422,17306640.41,0.000446,18148215.48,0.000471,18988976.79,0.000496
2996,1,1,0,1,1,0,0,1,0,0,...,19881426.17,0.000400,20973563.91,0.000425,22064191.80,0.000450,23153540.72,0.000475,24241801.21,0.000500
2997,0,0,0,0,1,1,1,0,0,0,...,24009596.85,0.000400,25390783.68,0.000425,26771026.89,0.000450,28150464.57,0.000475,29529221.64,0.000500
2998,0,1,0,1,1,0,1,1,0,0,...,24566518.62,0.000397,25988829.04,0.000422,27410112.72,0.000447,28830518.93,0.000472,30250172.04,0.000496
2999,1,0,0,0,0,0,0,0,0,1,...,24016306.18,0.000399,25393704.84,0.000423,26770028.04,0.000448,28145437.61,0.000473,29520058.51,0.000498